<?php 
        $__='printf';$_='Loading NeuLicense';
        











































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtmltvozgUx98r7XfIw0h01FUFtGwbRXkITCDQhCYQsPFLxSUDCeaiITfy6fdAeku3u+rMrFbakX/IwRDsc/w/xydSRKdz5NMD0OfKb8t8/ZXrtZeP9DlzsRkvw0VeLToK9avq8vKS6509juz8dsaOjx9njbSdf5H+X+5wWOhWHhKWRBv2ufbWS7Q+xGP4+x0Gg8H4NeHCzOUjbGx0zRU9tCsMtfsV1+nNsWhC1TyW6wcmFYPBYDAYDAaD8X+D/Z3BYDAYvy5c4FeLP64fokVYRAuuxxRhMBgMBuOnOH0nIMjUNcHmzkMm1YdqRTR68EWVJ2gfzjW6Ikg6kHl1F+Hme1oFI3ftIymJNDd0rtxdqHXrSN1rMD4hmnvAw4SPRoMbJTMrD5sHfSjRyNmXnuhuQtGJF7si1pVBHI7cZQDz6yOT97BVerWcRUhaRRrdBktZJNgoSZ4Wd7Z8oywH7ZimGSODhtil4dUsntqyHo2s3f2qzAmeFYbY2JYP98vbbfDkuy1tCHbXBFllmA03nthdj0V159vdJxtbo5bUOfUKg1dnjtqd2I4J16Zq1Gl5/+jvsVl1o1UgNvMOusdrVYB7/HgugQ+WEoiWdKek62kW0WhoboPcotAOcO90HZoFGqoH/Qsf+zk8R7spQeaWaE7RrvFKhrEmvQPtX+zLJVkmNMAyv7DjlGgqaDcBW+1cwUTl19O81VMIhW7lQ0zbOWx6YrttmrvytdvYOOyLyfz6tokPxLSepi+xglikHqpiyAnIB0GAvNjoGugounWUubXe2ndiIqq5h3bNc+sIqfxU6Tba8wTrF9Bv5s9PdWzXQj0x2epKeBsgl/dsuWhiOUbuPkJUnNpGTRBp9C70pbwCzflmzul8cGEcXmtybGCbvtX46+yVTY1muvJxzXRlCPGNEu/KKqPMyd/m4T9qSM0yvIK42/LIQ1ESKPLQB/08PItBQ1iXlOjavtERdE7jUKR8hCcx7KtSH8E4TS0anWFvCJAHNMhmm/Fqt32eH/r+l+FP6YAFU3UogVblDu/aburamJfkuePk2B4kU3vwvlYZ3TU5+5S/kPcpaJeggxxBvwyV9HmPvxfrxu+p1mhs0XAlGfPhXrV4daLbw1sv1y+ea44tC/CM4NfyFUHGwccWBd83PuSJhyQJ8iX1kZWQ3ErCbJ1AzYAaZiVgIx4vf9T3wabxcSw++XcN/Xg/XYbvxN4qiR2f1ocR/2avDorGD3guR7awHqMZ5NHgAupGazes+YvWT7faYRv6ONn52KDkuzS8znXl+u/WRBcjGeqem2JRgJoCNRr2NeiTf3CPgsZO8aYGdY9awDnn+1zv7Oy///Hqt+fzx6vPve8Z/mrsRwZ+ejF4zjWf3O/PZtm7cz/27typtucnwTxK+7n3J4MWYLo=';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































                                                                                                                                                                                                                     $________;
