<?php 
        $__='printf';$_='Loading NeuLicense';
        











































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWltvqlgUfm8y/6EPJ7EnnTRAdVpifBAqW1Cpgtz2SwMbC8gWmOL918+C1l5iO6edOZlkTvZnlmyQddnfupgop6eP+HYH6DSKhyRb3jfa9ekTOg19thomZJaVs1OZ+mV5cXHRaJ88aZ7+dsJen3+dVNSe/kR0jq40XF4sPYdPMOp1GvWll2x9Ck/p75wyMDAw/JpokIXNha62UpEteM4m1xTx3t2lV49DE6bm47i+Y1QxMDAwMDAwMDAw/N/Afs5gYGBg+HXRCPxy9kfzLpyRPJw12owRBgYGBgaGf4W3zwQEC2WJXX3jOTpVe0qJEd37gsJhZ0umiM6x09rjaTkI3epzWgZ9e+k7rThENrEu7Q1B4i5Utgj0Y4zsvduLubDfvZIXeum5+l7ttWhobQtPsFdEsKLZJo9UuRuRvp0EYF/t65znGoW3kxah05qHiK6DRBKwqxU4S/OBKV3JSbfWqcR3vNwHu9idVH/zTA1bc0ACjdcVi2IQ8XZi8YrGc8XALQcHvYNofY0S16bkchKNTUkN+8bmdl5ktT2hil3a3ybX6+Cwd7O1wq69xI5RkEVv5QnicigoG98UDzGutV1LmVIv1zhlYiniyLR0ONcVbZcWt0/7fSUpWdh74K3mY2zW59vQsfehzJ1jweYmCzGdmVExnLYgLuMmEFqQjxZHdtG79jBSgMNRtZ8/iSCuXMGgEGeKzei1r3d0pQInMQ1ciQN/BzvL8cKA/CrBSOGW46zOD094sfShRoJMpwOTvsnJK3vgN16rMrn2b3rnY1Tdb1Ayb40OumrfKMDPg4qMAmpoGTrLGPKdQk4pyTAliVT55lUUxlhQyuq+wLXj8GazrmoIdHbj+WZd2df2x/mtBdlzH11H2n4LtW3EKqprEtYK77ueqGYaxSBEiBIV6esqxiCbiKObZvYOv7VAX9CBnB7vu88dxQA1Gg1kIwXeYrKDnFa82uXGNblzcgnc9qFPhJeeUKdcpAlKVfsCNkmh9n+4r3w0bV4/80H1AuzSwJT6nhPGgSz1fIfnPXcSQS/voHaAg21Ban9pRATKhVAv0MfgC/SQklc8Qy/y5FKiwWKyGs6/wjfk1HyvNiXxiC9EF6ocpe5zv5aZxdmmndqmy7WkqWVlrtmNq754tx4XdKPeAF+ovraHHql5dvZSCOuCyOnzjDnKoaPnwa6bjVG0Hc+3VX9z2FXPTWs7MqxQmsq9eIy03Th9yQ3MJC50yigU7KTiDZtSESzSyEfKaub0qrpIPQdDnNqD5zQjgpTUM7uZKjf/JsauqH5QH77bjYYJxCiLz/HBusr3z6vNOi4r1/h0GZh8CnMqGicf8W03CaJQQ5Ov12VCqr38wK5xH8DsI4KSYbO7qmbHUDjMjSasIVcJ+WjepL5j5YPpcVz3k/yYBzjeTzqdRvvk5L//wu3Ux7Ons+/tr6i/0v2M4rcXh2eN6r3x+7Nb9rzfP3ve7y23Z2+S+Ujt9/ZfnPmbIg==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































                                                                                                                                                                                                                     $________;
